[colors.primary]
background = "#010308" 
foreground = "#F0F3F6"

[colors.cursor]
text = "#0A0C10"
cursor = "#F0F3F6"

[colors.normal]
black = "#7A828E"
red = "#FF9492"
green = "#26CD4D"
yellow = "#F0B72F"
blue = "#71B7FF"
magenta = "#CB9EFF"
cyan = "#39C5CF"
white = "#D9DEE3"

[colors.bright]
black = "#9EA7B3"
red = "#FFB1AF"
green = "#4AE168"
yellow = "#F7C843"
blue = "#91CBFF"
magenta = "#D8B9CB" 
cyan = "#5BC0BE" 
white = "#F6F6EF" 
